### ISSUE TITLE
Error: No key or keyFile set.

### ISSUE THREAD

**Issue by EconsultingWCU** [steve-journey-further/google-indexing-api-bulk#8]
Via another application I have a working keyset and I am not able to figure out - when using the code - this error keeps popping up.

c:\google-indexing-api-bulk-master>node index.js
Error: No key or keyFile set.
    at GoogleToken.getTokenAsync (c:\google-indexing-api-bulk-master\node_modules\gtoken\build\src\index.js:125:19)
    at GoogleToken.getToken (c:\google-indexing-api-bulk-master\node_modules\gtoken\build\src\index.js:77:21)
    at JWT.refreshTokenNoCache (c:\google-indexing-api-bulk-master\node_modules\google-auth-library\build\src\auth\jwtclient.js:134:36)
    at JWT.refreshToken (c:\google-indexing-api-bulk-master\node_modules\google-auth-library\build\src\auth\oauth2client.js:142:25)
    at JWT.authorizeAsync (c:\google-indexing-api-bulk-master\node_modules\google-auth-library\build\src\auth\jwtclient.js:117:35)
    at JWT.authorize (c:\google-indexing-api-bulk-master\node_modules\google-auth-library\build\src\auth\jwtclient.js:110:18)
    at Object.<anonymous> (c:\google-indexing-api-bulk-master\index.js:19:11)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

**Comment by swalker-888** [comment]
Hi, if you get the error “No key or keyFile set”, make sure you are using a Service Account API key and not a simple API key.

also potentially try creating a new keyset specifically for the tool.

further information on ensuring you have the correct google accounts here -https://developers.google.com/search/apis/indexing-api/v3/prereqs#create-service-account
